### ISSUE TITLE
Spree 3.0.0 with spree fancy dependency issues

### ISSUE THREAD

**Issue by umairpannu** [spree-contrib/spree_fancy#141] opened 2015-03-24 12:36 UTC
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.0.0)

  In Gemfile:
    spree (= 3.0.0) ruby depends on
      spree_core (= 3.0.0) ruby

```
spree_auth_devise (>= 0) ruby depends on
  spree_core (~> 3.0.0.beta) ruby

spree_auth_devise (>= 0) ruby depends on
  spree_core (~> 3.0.0.beta) ruby

spree_fancy (>= 0) ruby depends on
  spree_core (~> 2.1.0) ruby
```

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by umairpannu** [comment] 2015-03-24 12:36
gem file
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '4.2.1'

# Use sqlite3 as the database for Active Record

gem 'sqlite3'

# Use SCSS for stylesheets

gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets

gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .coffee assets and views

gem 'coffee-rails', '~> 4.1.0'

# See https://github.com/rails/execjs#readme for more supported runtimes

# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library

gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.

gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password

# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server

# gem 'unicorn'

# Use Capistrano for deployment

# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'spree', '3.0.0'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_fancy', :git => 'git://github.com/spree/spree_fancy.git', :branch => '2-1-stable'

**Comment by umairpannu** [comment] 2015-03-24 12:37
GIT
  remote: git://github.com/spree/spree_auth_devise.git
  revision: 07f16255c8e83cf5763f2c3510444ee1b4cdc4dd
  branch: 3-0-stable
  specs:
    spree_auth_devise (3.0.0)
      devise (~> 3.4.1)
      devise-encryptable (= 0.1.2)
      json
      multi_json
      spree_core (~> 3.0.0.beta)

GIT
  remote: git://github.com/spree/spree_gateway.git
  revision: d9305a348d259df0ffcb2a81ef79823b637539bc
  branch: 3-0-stable
  specs:
    spree_gateway (3.0.0.beta)
      spree_core (~> 3.0.0.beta)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemerchant (1.46.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.6.0)
      activerecord (>= 3.0)
    addressable (2.3.7)
    arel (6.0.0)
    autoprefixer-rails (5.1.7.1)
      execjs
      json
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.4.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    builder (3.2.2)
    byebug (4.0.3)
      columnize (= 0.9.0)
    camertron-eprun (1.1.0)
    cancancan (1.10.1)
    canonical-rails (0.0.8)
      rails (>= 3.1, < 5.0)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    cldr-plurals-runtime-rb (1.0.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1)
    colorize (0.7.5)
    columnize (0.9.0)
    css_parser (1.3.6)
      addressable
    debug_inspector (0.0.2)
    deface (1.0.1)
      colorize (>= 0.5.8)
      nokogiri (~> 1.6.0)
      polyglot
      rails (>= 3.1)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    erubis (2.7.0)
    execjs (2.4.0)
    ffaker (1.32.1)
    font-awesome-rails (4.3.0.0)
      railties (>= 3.2, < 5.0)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.3)
      activesupport (>= 4.1.0)
    highline (1.6.21)
    hike (1.2.3)
    htmlentities (4.3.3)
    httparty (0.13.3)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    jbuilder (2.2.12)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.3)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.3)
      railties (>= 3.2.16)
    json (1.8.2)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.4.3)
    mini_portile (0.6.2)
    minitest (5.5.1)
    monetize (1.1.0)
      money (~> 6.5.0)
    money (6.5.1)
      i18n (>= 0.6.4, <= 0.7.0)
    multi_json (1.11.0)
    multi_xml (0.5.5)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    orm_adapter (0.5.0)
    paperclip (4.2.1)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.3)
      mime-types
    paranoia (2.1.0)
      activerecord (~> 4.0)
    polyamorous (1.1.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    premailer (1.8.4)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.0)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)
    rabl (0.9.4.pre1)
      activesupport (>= 2.3.14)
    rack (1.6.0)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rdoc (4.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    sass (3.4.13)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    spree (3.0.0)
      spree_api (= 3.0.0)
      spree_backend (= 3.0.0)
      spree_cmd (= 3.0.0)
      spree_core (= 3.0.0)
      spree_frontend (= 3.0.0)
      spree_sample (= 3.0.0)
    spree_api (3.0.0)
      rabl (~> 0.9.4.pre1)
      spree_core (= 3.0.0)
      versioncake (~> 2.3.1)
    spree_backend (3.0.0)
      bootstrap-sass (~> 3.3.1)
      jquery-rails (~> 4.0.3)
      jquery-ui-rails (~> 5.0.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.0.0)
      spree_core (= 3.0.0)
      sprockets-rails (~> 2.2)
    spree_cmd (3.0.0)
      thor (~> 0.14)
    spree_core (3.0.0)
      activemerchant (~> 1.46.0)
      acts_as_list (~> 0.6)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0.0)
      ffaker (~> 1.16)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      httparty (~> 0.11)
      json (~> 1.7)
      kaminari (~> 0.15, >= 0.15.1)
      monetize (~> 1.1)
      paperclip (~> 4.2.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.0)
      ransack (~> 1.4.1)
      responders
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (= 0.9.2)
      twitter_cldr (~> 3.0)
    spree_frontend (3.0.0)
      bootstrap-sass (~> 3.3.1)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.0.3)
      spree_api (= 3.0.0)
      spree_core (= 3.0.0)
      sprockets-rails (~> 2.2)
    spree_sample (3.0.0)
      spree_core (= 3.0.0)
    spring (1.3.3)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    state_machines (0.2.2)
    state_machines-activemodel (0.1.2)
      activemodel (~> 4.1)
      state_machines (~> 0.2.0)
    state_machines-activerecord (0.2.0)
      activerecord (~> 4.1)
      state_machines-activemodel (~> 0.1.0)
    stringex (2.5.2)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    truncate_html (0.9.2)
    turbolinks (2.5.3)
      coffee-rails
    twitter_cldr (3.1.2)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0.0)
      json
      tzinfo
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.1.2)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.1.0)
  jbuilder (~> 2.0)
  jquery-rails
  rails (= 4.2.1)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spree (= 3.0.0)
  spree_auth_devise!
  spree_gateway!
  spring
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

**Comment by JDutil** [comment] 2015-03-24 14:45
This is a duplicate of:
https://github.com/spree-contrib/spree_fancy/issues/138
https://github.com/spree-contrib/spree_fancy/issues/139

Spree 3 no longer uses the skeleton css framework that this theme is based upon.  We have no intentions of upgrading this theme to work with Spree 3.  If someone would like to contribute a PR to make it happen I could review it, but I would not count on it.

**Closed as completed by JDutil** 2015-03-24 14:45 UTC

**Comment by umairpannu** [comment] 2015-03-24 16:49
thanks a lot.
