### ISSUE TITLE
spree dependency issue with spree_core 2.4.3

### ISSUE THREAD

**Issue by jthurston** [spree-contrib/spree_fancy#137] opened 2015-02-11 20:01 UTC
Clean fresh working install for Spree Commerce 2.4.3

Running the command:
bundle install

Receive this error:

Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_fancy (>= 0) ruby depends on
      spree_core (~> 2.3.0.beta) ruby

    spree_gateway (>= 0) ruby depends on
      spree_core (2.4.3)

Gemfile section:

gem 'spree_fancy', :github => 'spree/spree_fancy'
gem 'spree', '2.4.3'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'

Do I need to go back to 2.3?

**Comment by JDutil** [comment] 2015-02-11 21:05
duplicate of #131 yes you need to use 2.3 or upgrade this extension to work with 2.4

**Closed by JDutil** 2015-02-11 21:05 UTC
